"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-$f86+e5zok*(=posx*sk4&bcx-3jlbxh(4(mmg3q0t95s2d(s0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

allowed_hosts = ['localhost', '127.0.0.1', '0.0.0.0']
for host in os.getenv('ALLOWED_HOSTS', '').split(','):
    host = host.strip()
    if host:
        allowed_hosts.append(host)

vercel_host = os.getenv('VERCEL_URL')
if vercel_host:
    allowed_hosts.append(vercel_host)

ALLOWED_HOSTS = allowed_hosts

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'users',
    'projects',
    'issues',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'users.User'

cors_origins = [
    'http://localhost:5173',
    'http://localhost:3000',
    'http://10.169.235.240:5173',
]
frontend_url = os.getenv('FRONTEND_URL')
if frontend_url:
    cors_origins.append(frontend_url)

CORS_ALLOWED_ORIGINS = list(dict.fromkeys(cors_origins))
CORS_ALLOWED_ORIGIN_REGEXES = [r'^https://.*\.vercel\.app$']

# Allow any origin during LAN development
CORS_ALLOW_ALL_ORIGINS = DEBUG

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:3000',
    'http://127.0.0.1:5173',
    'http://10.169.235.240:5173',
]
if frontend_url:
    CSRF_TRUSTED_ORIGINS.append(frontend_url)
if vercel_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{vercel_host}')
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'static_root'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Hosted Postgres when DATABASE_URL (or Vercel/Neon's POSTGRES_URL) is set; SQLite for local development.
# Serverless hosts like Vercel can't keep a SQLite file, so production must use DATABASE_URL.
_database_url = os.getenv('DATABASE_URL') or os.getenv('POSTGRES_URL')
if _database_url:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(_database_url, conn_max_age=0, ssl_require=True),
    }
    # Poolers (pgbouncer) don't support server-side cursors.
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static_root']

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email Configuration (Supports Gmail SMTP & Console Fallback)
from dotenv import load_dotenv

# Load .env file from the backend directory
load_dotenv(BASE_DIR / '.env')

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Send notification emails in the background so saving never waits on the mail server.
# (Off for tests, and by default on Vercel where a request's threads are cut off when it ends.)
EMAIL_SEND_ASYNC = os.getenv('EMAIL_SEND_ASYNC', '0' if os.getenv('VERCEL') else '1') == '1' and 'test' not in sys.argv

# Calendar reminders
REMINDER_TIME_ZONE = os.getenv('REMINDER_TIME_ZONE', 'Asia/Kolkata')   # zone that calendar dates/times are read in
REMINDER_DEFAULT_HOUR = int(os.getenv('REMINDER_DEFAULT_HOUR', 9))     # entries without a time go out at this hour
REMINDER_SCHEDULER = os.getenv('REMINDER_SCHEDULER', '1') == '1'       # in-process checker (not for serverless)
CRON_SECRET = os.getenv('CRON_SECRET', '')                             # protects GET /api/cron/reminders/

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'users.email_backend.CertifiSMTPEmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', f'Jira Software <{EMAIL_HOST_USER}>')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'Jira Software <noreply@jira-software.local>'


