# Generated by Django 5.2.17 on 2026-10-06 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_calendar_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdoc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_docs/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='projectdoc',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='projectdoc',
            name='file_type',
            field=models.CharField(choices=[('MARKDOWN', 'Markdown'), ('PDF', 'PDF Document'), ('DOCX', 'Word Document'), ('XLSX', 'Excel Spreadsheet'), ('OTHER', 'Other File')], default='MARKDOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='projectdoc',
            name='raw_text',
            field=models.TextField(blank=True, help_text='Extracted plain text content from uploaded file'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectdoc',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectdoc',
            name='template_type',
            field=models.CharField(choices=[('STATUS', 'Project Status / Weekly Report'), ('TIMELINE', 'Timeline & Project Plan'), ('RESOURCE', 'Resource / Team Document'), ('PRD', 'Product Requirements (PRD)'), ('ARCHITECTURE', 'Architecture & System Design'), ('RETRO', 'Sprint Retrospective'), ('MEETING', 'Meeting Notes & Decisions'), ('CUSTOM', 'Custom Document')], default='CUSTOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ProjectIntelligenceSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('OFF_TRACK', 'Off Track')], default='ON_TRACK', max_length=20)),
                ('health_rationale', models.TextField(blank=True, help_text='Deterministic justification for health state')),
                ('current_phase', models.CharField(blank=True, help_text='Active phase / workstream', max_length=200)),
                ('executive_summary', models.TextField(blank=True, help_text='Concise 4-5 bullet executive briefing')),
                ('signals_count', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_summary', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PHASE', 'Active Phase / Workstream'), ('MILESTONE', 'Milestone / Deliverable'), ('RISK', 'Project Risk'), ('BLOCKER', 'Active Blocker'), ('CHALLENGE', 'Project Challenge'), ('DEPENDENCY', 'Technical or External Dependency'), ('UPDATE', 'Status Update'), ('DECISION', 'Key Decision'), ('RESOURCE_NOTE', 'Resource / Team Allocation Note')], default='UPDATE', max_length=25)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='ACTIVE', help_text='e.g. ACTIVE, RESOLVED, DELAYED, COMPLETED', max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=15)),
                ('target_date', models.DateField(blank=True, help_text='Target milestone or resolution date', null=True)),
                ('source_location', models.CharField(blank=True, help_text='Page, section heading, or sheet cell reference', max_length=255)),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score from 0.0 to 1.0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='projects.project')),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='projects.projectdoc')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
